[program:allitrader-celery-beat]
command=/var/www/allitrader/.venv/bin/celery -A Main.celery beat --loglevel=info
directory=/var/www/allitrader
user=www-data
group=www-data
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=60
stdout_logfile=/var/www/allitrader/logs/celery_beat_stdout.log
stderr_logfile=/var/www/allitrader/logs/celery_beat_stderr.log
environment=PROJECT_NAME="Main",DJANGO_SETTINGS_MODULE="Main.settings"
