[program:allitrader-gunicorn]
command=/var/www/allitrader/.venv/bin/gunicorn Main.wsgi:application --bind 127.0.0.1:8000 --workers 3 --timeout 30 --access-logfile /var/www/allitrader/logs/gunicorn_access.log --error-logfile /var/www/allitrader/logs/gunicorn_error.log
directory=/var/www/allitrader
user=www-data
group=www-data
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=60
stdout_logfile=/var/www/allitrader/logs/gunicorn_stdout.log
stderr_logfile=/var/www/allitrader/logs/gunicorn_stderr.log
environment=PROJECT_NAME="Main",DJANGO_SETTINGS_MODULE="Main.settings"
