# Generated by Django 5.2.14 on 2026-07-15 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSearchResult',
            fields=[
                ('type_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, help_text='Персонаж, которому принадлежит список', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Список_наблюдения', to='eveonline.evecharacter')),
            ],
            options={
                'verbose_name': 'Результат поиска типа предмета',
                'verbose_name_plural': 'Результаты поиска типов предметов',
                'indexes': [models.Index(fields=['type_name'], name='traders_typ_type_na_6f77be_idx'), models.Index(fields=['group_name'], name='traders_typ_group_n_cd6f98_idx'), models.Index(fields=['category_name'], name='traders_typ_categor_a351f5_idx')],
            },
        ),
    ]
