# Generated by Django 5.2.14 on 2026-06-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveItemType',
            fields=[
                ('type_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Тип предмета',
                'verbose_name_plural': 'Типы предметов',
            },
        ),
        migrations.CreateModel(
            name='EveLocation',
            fields=[
                ('location_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_singleton', models.BooleanField()),
                ('item_id', models.PositiveBigIntegerField(unique=True)),
                ('location_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, help_text='Персонаж, которому принадлежит актив', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eveonline.evecharacter')),
                ('corporation', models.ForeignKey(blank=True, help_text='Корпорация, которой принадлежит актив', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eveonline.evecorporation')),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='trader.eveitemtype')),
                ('location', models.ForeignKey(blank=True, help_text='Локация, где находится актив', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='trader.evelocation')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
                'indexes': [models.Index(fields=['is_singleton'], name='trader_asse_is_sing_cf027f_idx'), models.Index(fields=['location'], name='trader_asse_locatio_de0520_idx'), models.Index(fields=['type_id'], name='trader_asse_type_id_84e062_idx'), models.Index(fields=['character'], name='trader_asse_charact_c314fd_idx'), models.Index(fields=['corporation'], name='trader_asse_corpora_0db78e_idx')],
            },
        ),
    ]
