# Generated by Django 5.2.14 on 2026-06-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_eveitemtype_category_id_eveitemtype_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='trader.eveitemtype')),
            ],
            options={
                'verbose_name': 'Порог алерта',
                'verbose_name_plural': 'Пороги алертов',
                'indexes': [models.Index(fields=['user_id'], name='trader_aler_user_id_702067_idx'), models.Index(fields=['type_id'], name='trader_aler_type_id_732d6e_idx')],
                'unique_together': {('user_id', 'type_id')},
            },
        ),
    ]
