name: Deploy to Production

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}  # Возможность запуска вручную

jobs:
  deploy:
    name: 🚀 Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
    - name: 🛎️ Notify - Deployment started
      uses: appleboy/discord-action@master
      if: always()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#8b9b9c"
        username: "GitHub Bot"
        message: |
          Deploy started for ${{ github.sha }}

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: | 
          cd /var/www/allitrader
          echo "🔄 Cleaning git state..."
          git fetch origin
          git reset --hard origin/master
          git clean -fd
          echo "✅ Git state cleaned and updated"
          
          echo "📦 Activate venv and install requirements"
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          echo "🔄 Run migrations"
          python manage.py makemigrations
          python manage.py migrate --noinput
          
          echo "📊 Collect static files"
          python manage.py collectstatic --noinput
          
          echo "🔄 Install supervisor configurations"
          sudo mkdir -p /etc/supervisor/conf.d
          sudo cp /var/www/allitrader/scripts/supervisor/*.conf /etc/supervisor/conf.d/
          sudo supervisorctl reread
          sudo supervisorctl update
          
          echo "🔄 Restart services via supervisor"
          sudo supervisorctl restart allitrader:*
          
          echo "✅ Deploy finished"


    - name: 🛎️ Notify - Success
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#8b9b9c"
        username: "GitHub Bot"
        message: |
          ✅ Deploy succeeded: ${{ github.sha }}

    - name: 🛎️ Notify - Failed
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#8b9b9c"
        username: "GitHub Bot"
        message: |
          ❌ Deploy failed: ${{ github.sha }}